@Bigai_TaskManager_Api_HostAddress = http://localhost:5000

@ProjectId = 1

@UserToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlRhc2tNYW5hZ2VyIiwic3ViIjoiVGFza01hbmFnZXIiLCJqdGkiOiI3N2MyNGNjOSIsInJvbGUiOiJVc2VyIiwidXNlcklkIjoiNDYyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDQxMSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzUyIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJdLCJuYmYiOjE3MzE2OTQ1NDQsImV4cCI6MTc2MzIzMDU0NCwiaWF0IjoxNzMxNjk0NTQ3LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.sHQC7gqtY1_RCCo8v4H6b6nBj0iYzuIM5bjoOkvdZUo

@ManagerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlRhc2tNYW5hZ2VyIiwic3ViIjoiVGFza01hbmFnZXIiLCJqdGkiOiIyNDY4MmZiIiwicm9sZSI6Ik1hbmFnZXIiLCJ1c2VySWQiOiI3IiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDQxMSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzUyIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJdLCJuYmYiOjE3MzE2OTM4OTcsImV4cCI6MTc2MzIyOTg5NywiaWF0IjoxNzMxNjkzOTAwLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.PFVlGyBAu9oa9DAXD6o_E8fnOSG86nGyxIzTayEhfRU


### Create a new project.
POST {{Bigai_TaskManager_Api_HostAddress}}/api/projects/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{UserToken}}
#Authorization: Bearer {{ManagerToken}}

{
  "name": "A sample name of project"
}


### Gets all registered projects of a user.
GET {{Bigai_TaskManager_Api_HostAddress}}/api/projects/users/{{ProjectId}}
Accept: application/json
Authorization: Bearer {{UserToken}}
#Authorization: Bearer {{ManagerToken}}

### Gets a project by its identifier.
GET {{Bigai_TaskManager_Api_HostAddress}}/api/projects/{{ProjectId}}
Accept: application/json
Authorization: Bearer {{UserToken}}
#Authorization: Bearer {{ManagerToken}}

### Gets a project by its identifier.
DELETE {{Bigai_TaskManager_Api_HostAddress}}/api/projects/{{ProjectId}}
Accept: application/json
Authorization: Bearer {{UserToken}}
#Authorization: Bearer {{ManagerToken}}
